Repository RangerDigital/gintoki, pull requests merged in 2021-06, with the labels that each got.

#2 Add auth module, /users route
  backend/configs/config.js
  backend/hooks/authHook.js
  backend/hooks/ownerHook.js
  backend/models/users.js
  backend/package-lock.json
  backend/package.json
  backend/routes/auth.js
  backend/routes/users.js
  backend/server.js
  backend/services/AuthService.js
  backend/services/UserService.js
  backend/templates/magic.html
Labels: enhancement

#3 Update template
  backend/services/AuthService.js
  backend/templates/magic.html
Labels: enhancement

#4 Add lockers route
  backend/models/lockers.js
  backend/routes/items.js
  backend/routes/lockers.js
  backend/server.js
  backend/services/ItemService.js
  backend/services/LockerService.js
Labels: enhancement

#5 Add commands functionality
  backend/routes/lockers.js
  backend/services/ItemService.js
  backend/services/LockerService.js
Labels: enhancement

#7 Add tests framework
  backend/package-lock.json
  backend/package.json
  backend/tests/auth.test.js
  backend/tests/db.js
  backend/tests/helpers.js
  backend/tests/users.test.js
Labels: enhancement

#8 Add geo search
  backend/models/lockers.js
  backend/routes/lockers.js
  backend/services/LockerService.js
Labels: enhancement

#9 Add items test
  backend/tests/helpers.js
  backend/tests/items.test.js
Labels: enhancement

#10 Update /items doc
  backend/routes/items.js
Labels: documentation, enhancement

#11 Add micropython scaffolding
  controller/boot.py
  controller/config.py
  controller/main.py
Labels: enhancement

#12 Refactor /commands with headers
  backend/routes/lockers.js
  controller/main.py
Labels: enhancement

#13 Refactor protected /locker route
  backend/routes/lockers.js
Labels: enhancement

#14 Fix protected keyword
  backend/routes/lockers.js
Labels: bug

#16 Add auth and home view
  frontend/src/App.vue
  frontend/src/components/TopNavigation.vue
  frontend/src/router/index.js
  frontend/src/views/Auth.vue
  frontend/src/views/Home.vue
  frontend/src/views/Items.vue
  frontend/src/views/Outh.vue
Labels: enhancement

#18 Add favicon
  frontend/public/index.html
Labels: enhancement

#21 Refactor frontend
  backend/routes/items.js
  backend/services/ItemService.js
  frontend/src/components/TopNavigation.vue
  frontend/src/router/index.js
  frontend/src/views/Auth.vue
  frontend/src/views/CreateItem.vue
  frontend/src/views/Home.vue
  frontend/src/views/Items.vue
  frontend/tailwind.config.js
Labels: enhancement

#22 Change site style
  frontend/src/components/TopNavigation.vue
  frontend/src/views/Auth.vue
  frontend/src/views/Create.vue
  frontend/src/views/CreateItem.vue
  frontend/src/views/Home.vue
  frontend/src/views/Items.vue
  frontend/tailwind.config.js
Labels: enhancement
